# Generated by Django 6.0.5 on 2026-06-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('In-App', 'In-App'), ('Email', 'Email'), ('SMS', 'SMS'), ('Load Assigned', 'Load Assigned to Driver')], default='In-App', max_length=20),
        ),
        migrations.CreateModel(
            name='LoadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('In-App', 'In-App'), ('SMS', 'SMS')], max_length=20)),
                ('message', models.TextField(help_text='Full message sent to driver')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Number used at time of sending', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Read', 'Read')], default='Pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apps.loadassignment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_notifications', to='apps.driver')),
            ],
            options={
                'db_table': 'load_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
