# Generated by Django 6.0.5 on 2026-06-16 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_load_delivery_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
