# Generated by Django 6.0.5 on 2026-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_trip_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='complete_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
