# Generated by Django 6.0.5 on 2026-06-20 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_load_destination_latitude_load_destination_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PM Due Soon', 'PM Due Soon'), ('PM Overdue', 'PM Overdue'), ('Truck Out of Service', 'Truck Out of Service'), ('Truck Inspection Required', 'Truck Inspection Required'), ('Repair Not Approved', 'Repair Not Approved (24h)'), ('Repeated Repair', 'Repeated Repair (3x in 90 days)'), ('High Maintenance Cost', 'High Maintenance Cost'), ('Long Downtime', 'Long Downtime (48h+)'), ('Parts Reorder', 'Parts Reorder Needed'), ('Invoice Due', 'Vendor Invoice Due'), ('DOT Inspection Due', 'Annual DOT Inspection Due')], max_length=25),
        ),
        migrations.CreateModel(
            name='dispatch_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='dispatcher_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='apps.dispatch_department'),
        ),
        migrations.CreateModel(
            name='fleet_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='fleet_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='apps.fleet_department'),
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.truck')),
            ],
        ),
        migrations.DeleteModel(
            name='LoadNotification',
        ),
    ]
